// examples/vue/pages/specialities/+Page.vue
<script setup>
import { useI18n } from 'vue-i18n'
import { useData } from 'vike-vue/useData'
import { usePageContext } from 'vike-vue/usePageContext'
import { useI18nRoute } from 'vike-i18n-routing'

const { t } = useI18n({ useScope: 'global' })
const data = useData()
const pageContext = usePageContext()
const { localizePath } = useI18nRoute(pageContext)
const locale = pageContext.locale

function filterHref(filter) {
  return localizePath(`/specialities?focus=${filter.variants[locale]}`)
}
</script>

<template>
  <div>
    <h1>{{ t('specialities.title') }}</h1>
    <p>{{ t('specialities.body') }}</p>

    <div class="filters">
      <a
        :href="localizePath('/specialities')"
        :class="{ active: data.activeFocus === null }"
      >
        {{ t('specialities.filters.all') }}
      </a>
      <a
        v-for="filter in data.filters"
        :key="filter.key"
        :href="filterHref(filter)"
        :class="{ active: data.activeFocus === filter.key }"
      >
        {{ t(`specialities.filters.${filter.key}`) }}
      </a>
    </div>

    <ul class="list">
      <li v-for="item in data.specialities" :key="item.slug">
        <a :href="localizePath(`/specialities/${item.variants.speciality[locale]}`)">
          {{ item.title[locale] }}
        </a>
        <p>{{ item.description[locale] }}</p>
      </li>
    </ul>
  </div>
</template>

<style scoped>
.filters {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
  margin-bottom: 20px;
}

.filters a.active {
  font-weight: 700;
  text-decoration: none;
}

.list {
  display: grid;
  gap: 16px;
  padding: 0;
  list-style: none;
}
</style>

// examples/solid/pages/specialities/+Page.tsx
import { For } from 'solid-js'
import { useData } from 'vike-solid/useData'
import { usePageContext } from 'vike-solid/usePageContext'
import { useI18nRoute } from 'vike-i18n-routing'
import { createTranslator } from '../../i18n'
import type { SpecialityFocusFilter, SpecialityRecord } from './data'

export { Page }

type PageData = {
  activeFocus: string | null
  filters: SpecialityFocusFilter[]
  specialities: SpecialityRecord[]
}

function Page() {
  const data = useData<PageData>()
  const pageContext = usePageContext()
  const { localizePath } = useI18nRoute(pageContext)
  const t = createTranslator(() => pageContext.locale)

  function filterHref(filter: PageData['filters'][number]) {
    return localizePath(`/specialities?focus=${filter.variants[pageContext.locale]}`)
  }

  return (
    <div>
      <h1>{t('specialities.title')}</h1>
      <p>{t('specialities.body')}</p>

      <div style={filtersStyle}>
        <a
          href={localizePath('/specialities')}
          style={data.activeFocus === null ? activeLinkStyle : undefined}
        >
          {t('specialities.filters.all')}
        </a>
        <For each={data.filters}>
          {(filter) => (
            <a
              href={filterHref(filter)}
              style={data.activeFocus === filter.key ? activeLinkStyle : undefined}
            >
              {t(`specialities.filters.${filter.key}` as 'specialities.filters.frontend' | 'specialities.filters.backend')}
            </a>
          )}
        </For>
      </div>

      <ul style={listStyle}>
        <For each={data.specialities}>
          {(item) => (
            <li>
              <a href={localizePath(`/specialities/${item.variants.speciality[pageContext.locale]}`)}>
                {item.title[pageContext.locale as 'en' | 'ru']}
              </a>
              <p>{item.description[pageContext.locale as 'en' | 'ru']}</p>
            </li>
          )}
        </For>
      </ul>
    </div>
  )
}

const filtersStyle = {
  display: 'flex',
  'flex-wrap': 'wrap',
  gap: '12px',
  'margin-bottom': '20px',
}

const activeLinkStyle = {
  'font-weight': 700,
  'text-decoration': 'none',
}

const listStyle = {
  display: 'grid',
  gap: '16px',
  padding: 0,
  'list-style': 'none',
}
