// examples/static/pages/index/+Page.vue
<script setup>
import { usePageContext } from 'vike-vue/usePageContext'
import { useI18nRoute } from 'vike-i18n-routing'
import { getMessages } from '../../messages'

const pageContext = usePageContext()
const { localizePath } = useI18nRoute(pageContext)
const messages = getMessages(pageContext.locale)
</script>

<template>
  <section class="panel">
    <h1>{{ messages.home.title }}</h1>
    <p>{{ messages.home.body }}</p>
    <a class="cta" :href="localizePath('/specialities')">
      {{ messages.home.cta }}
    </a>
  </section>
</template>

<style scoped>
.panel {
  padding: 24px;
  border: 1px solid #e5e7eb;
  border-radius: 20px;
  background: #fff;
}

.cta {
  display: inline-flex;
  margin-top: 16px;
  color: #0f172a;
  font-weight: 700;
}
</style>

// examples/solid/pages/index/+Page.tsx
import { usePageContext } from 'vike-solid/usePageContext'
import { useI18nRoute } from 'vike-i18n-routing'
import { createTranslator } from '../../i18n'

export { Page }

function Page() {
  const pageContext = usePageContext()
  const { localizePath } = useI18nRoute(pageContext)
  const t = createTranslator(() => pageContext.locale)

  return (
    <div>
      <h1>{t('home.title')}</h1>
      <p>{t('home.currentLocale', { locale: pageContext.locale })}</p>
      <p>
        {t('home.tryDynamicList')}{' '}
        <a href={localizePath('/specialities', pageContext.locale)}>
          {t('layout.specialities')}
        </a>
      </p>
    </div>
  )
}
