// examples/basic/pages/index/+Page.vue
<script setup>
import { useI18n } from 'vue-i18n'
import { usePageContext } from 'vike-vue/usePageContext'
import { useI18nRoute } from 'vike-i18n-routing/vue'

const { t } = useI18n({ useScope: 'global' })
const { locale, localizePath } = useI18nRoute(usePageContext())
</script>

<template>
  <div>
    <h1>{{ t('home.title') }}</h1>
    <p>{{ t('home.currentLocale', { locale }) }}</p>
    <p>
      {{ t('home.tryDynamicList') }}
      <a :href="localizePath('/specialities', locale)">
        {{ t('layout.specialities') }}
      </a>
    </p>
  </div>
</template>

// examples/solid/pages/index/+Page.tsx
import { usePageContext } from 'vike-solid/usePageContext'
import { useI18nRoute } from 'vike-i18n-routing/solid'
import { createTranslator } from '../../i18n'

export { Page }

function Page() {
  const { locale, localizePath } = useI18nRoute(usePageContext())
  const t = createTranslator(locale)

  return (
    <div>
      <h1>{t('home.title')}</h1>
      <p>{t('home.currentLocale', { locale: locale() })}</p>
      <p>
        {t('home.tryDynamicList')}{' '}
        <a href={localizePath('/specialities', locale())}>
          {t('layout.specialities')}
        </a>
      </p>
    </div>
  )
}
