// examples/react/pages/+Layout.tsx
import type { ReactNode } from 'react'
import { IntlProvider, useIntl } from 'react-intl'
import { usePageContext } from 'vike-react/usePageContext'
import { useI18nRoute } from 'vike-i18n-routing/react'
import { messages } from '../messages'

export { Layout }

function Layout({ children }: { children: ReactNode }) {
  const pageContext = usePageContext()
  const locale = (pageContext.locale ?? 'en') as keyof typeof messages

  return (
    <IntlProvider locale={locale} messages={messages[locale]} defaultLocale="en">
      <LayoutContent>{children}</LayoutContent>
    </IntlProvider>
  )
}

function LayoutContent({ children }: { children: ReactNode }) {
  const intl = useIntl()
  const pageContext = usePageContext()
  const { locale, localeConfig, routeConfig, localizePath } = useI18nRoute(pageContext)
  const locales = Object.keys(localeConfig.locales)

  function switchLocale(nextLocale: string) {
    return localizePath(routeConfig.canonicalUrl, nextLocale, { prefix: true })
  }

  return (
    <div style={layoutStyle}>
      <header style={headerStyle}>
        <div>
          <a href={localizePath('/')} style={brandStyle}>
            {intl.formatMessage({ id: 'layout.brand' })}
          </a>
        </div>

        <nav style={navStyle}>
          <a href={localizePath('/')}>{intl.formatMessage({ id: 'layout.home' })}</a>
          <a href={localizePath('/about')}>{intl.formatMessage({ id: 'layout.about' })}</a>
          <a href={localizePath('/specialities')}>{intl.formatMessage({ id: 'layout.specialities' })}</a>
        </nav>

        <nav aria-label={intl.formatMessage({ id: 'layout.switchLocale' })} style={navStyle}>
          {locales.map((supportedLocale) => (
            <a
              key={supportedLocale}
              href={switchLocale(supportedLocale)}
              style={supportedLocale === locale ? activeLocaleStyle : undefined}
            >
              {supportedLocale.toUpperCase()}
            </a>
          ))}
        </nav>
      </header>

      <main style={contentStyle}>{children}</main>

      <footer>
        <pre>{JSON.stringify(routeConfig, null, 2)}</pre>
      </footer>
    </div>
  )
}

const layoutStyle = {
  maxWidth: '960px',
  margin: '0 auto',
  padding: '24px',
  fontFamily: '"Helvetica Neue", Arial, sans-serif',
}

const headerStyle = {
  display: 'flex',
  flexWrap: 'wrap',
  alignItems: 'center',
  justifyContent: 'space-between',
  gap: '16px',
  paddingBottom: '16px',
  marginBottom: '24px',
  borderBottom: '1px solid #d4d4d8',
} as const

const brandStyle = {
  color: 'inherit',
  fontSize: '20px',
  fontWeight: 700,
  textDecoration: 'none',
}

const navStyle = {
  display: 'flex',
  flexWrap: 'wrap',
  gap: '12px',
} as const

const activeLocaleStyle = {
  fontWeight: 700,
  textDecoration: 'none',
}

const contentStyle = {
  display: 'grid',
  gap: '16px',
}

// examples/solid/pages/+Layout.tsx
import { For, createMemo, type JSX } from 'solid-js'
import { usePageContext } from 'vike-solid/usePageContext'
import { useI18nRoute } from 'vike-i18n-routing/solid'
import { createTranslator } from '../i18n'

export { Layout }

function Layout(props: { children: JSX.Element }) {
  const pageContext = usePageContext()
  const { locale, localeConfig, routeConfig, localizePath } = useI18nRoute(pageContext)
  const locales = createMemo(() => Object.keys(localeConfig().locales))
  const t = createTranslator(locale)

  function switchLocale(nextLocale: string) {
    return localizePath(routeConfig().canonicalUrl, nextLocale, { prefix: true })
  }

  return (
    <div style={layoutStyle}>
      <header style={headerStyle}>
        <div>
          <a href={localizePath('/')} style={brandStyle}>
            {t('layout.brand')}
          </a>
        </div>

        <nav style={navStyle}>
          <a href={localizePath('/')}>{t('layout.home')}</a>
          <a href={localizePath('/about')}>{t('layout.about')}</a>
          <a href={localizePath('/specialities')}>{t('layout.specialities')}</a>
        </nav>

        <nav aria-label={t('layout.switchLocale')} style={navStyle}>
          <For each={locales()}>
            {(supportedLocale) => (
              <a
                href={switchLocale(supportedLocale)}
                style={supportedLocale === locale() ? activeLocaleStyle : undefined}
              >
                {supportedLocale.toUpperCase()}
              </a>
            )}
          </For>
        </nav>
      </header>

      <main style={contentStyle}>{props.children}</main>

      <footer>
        <pre>{JSON.stringify(routeConfig(), null, 2)}</pre>
      </footer>
    </div>
  )
}

const layoutStyle = {
  'max-width': '960px',
  margin: '0 auto',
  padding: '24px',
  'font-family': '"Helvetica Neue", Arial, sans-serif',
}

const headerStyle = {
  display: 'flex',
  'flex-wrap': 'wrap',
  'align-items': 'center',
  'justify-content': 'space-between',
  gap: '16px',
  'padding-bottom': '16px',
  'margin-bottom': '24px',
  'border-bottom': '1px solid #d4d4d8',
}

const brandStyle = {
  color: 'inherit',
  'font-size': '20px',
  'font-weight': 700,
  'text-decoration': 'none',
}

const navStyle = {
  display: 'flex',
  'flex-wrap': 'wrap',
  gap: '12px',
}

const activeLocaleStyle = {
  'font-weight': 700,
  'text-decoration': 'none',
}

const contentStyle = {
  display: 'grid',
  gap: '16px',
}
