// examples/vue/pages/specialities/@speciality/+Page.vue
<script setup>
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useData } from 'vike-vue/useData'
import { usePageContext } from 'vike-vue/usePageContext'

const { t } = useI18n({ useScope: 'global' })
const pageContext = usePageContext()
const data = useData()

const speciality = computed(() => data.speciality)
</script>

<template>
  <div>
    <h1>{{ t('speciality.title', { speciality }) }}</h1>
    <p>{{ data.description }}</p>
    <p>
      {{ t('speciality.currentUrl') }}
      <code>{{ pageContext.i18nRoute.routeConfig.currentLocaleUrl }}</code>
    </p>

    <pre>{{ data }}</pre>
  </div>
</template>

// examples/react/pages/specialities/@speciality/+Page.tsx
import { useIntl } from 'react-intl'
import { useData } from 'vike-react/useData'
import { usePageContext } from 'vike-react/usePageContext'

export { Page }

type PageData = {
  speciality: string
  description: string
}

function Page() {
  const intl = useIntl()
  const data = useData<PageData>()
  const pageContext = usePageContext()

  return (
    <div>
      <h1>{intl.formatMessage({ id: 'speciality.title' }, { speciality: data.speciality })}</h1>
      <p>{data.description}</p>
      <p>
        {intl.formatMessage({ id: 'speciality.currentUrl' })}{' '}
        <code>{pageContext.i18nRoute.routeConfig.currentLocaleUrl}</code>
      </p>

      <pre>{JSON.stringify(data, null, 2)}</pre>
    </div>
  )
}
